HandyRides Lab3/HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name="index.html")),
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls'))
]

HandyRides Lab3/rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('create_rides', views.create_rides, name = 'create_rides'),
    path('search_results', views.display_rides, name = 'display_rides')

]

HandyRides Lab3/rides/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
  first_name = models.CharField(max_length=64)
  last_name = models.CharField(max_length=64)
  email = models.CharField(max_length=64)
  phone_number = models.CharField(max_length=12)
  origination_city = models.CharField(max_length=64)
  origination_state = models.CharField(max_length=2)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  vehicle_type = models.CharField(max_length=64)
  vehicle_model = models.CharField(max_length = 64)
  date = models.DateField()
  time = models.TimeField()
  taking_passengers = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)

HandyRides Lab3/rides/forms.py
from django import forms
from .models import Person
from django.forms import DateInput, TimeInput, TextInput


class RideForm(forms.Form):
  origination_city = forms.CharField(label='Origination City', max_length=64, required=False)
  origination_state = forms.CharField(label='Origination State', max_length=2, required=False)
  destination_city = forms.CharField(label='Destination City', max_length=64, required=False)
  destination_state = forms.CharField(label='Destination State', max_length=2, required=False)
  date = forms.DateField(required = False, widget=forms.DateInput(attrs={'placeholder': 'Select a date', 'type': 'date'}))
  time = forms.TimeField(required = False, widget=forms.TimeInput(attrs={'placeholder': 'Select a time', 'type': 'time'}))
  seats = forms.IntegerField(required = False)


class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person

    widgets = {
            'date': DateInput(attrs={'placeholder': 'Select a date', 'type': 'date'}),
            'time': TimeInput(attrs={'placeholder': 'Select a time', 'type': 'time'}),
            'phone_number':TextInput(attrs={'placeholder': '999-999-9999'}),
            'email': TextInput(attrs= {'placeholder': 'example@example.com'}),
            'vehicle_type': TextInput(attrs= {'placeholder': 'Nissan'}),
            'vehicle_model': TextInput(attrs= {'placeholder': 'Sentra'}),
        }
    exclude = []

HandyRides Lab3/rides/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from .forms import RideForm, NewRideForm

from .models import Person

# relative import of forms
from .forms import RideForm

# Create your views here.


def index(request):
  context = {}

  possible_entries = ['origination_city', 'origination_state', 'destination_city', 'destination_state', 'date', 'time', 'seats']
  if request.method == 'GET' and any(field in request.GET for field in possible_entries):
      origination_city = request.GET.get('origination_city', '')
      origination_state = request.GET.get('origination_state', '')
      destination_city = request.GET.get('destination_city', '')
      destination_state = request.GET.get('destination_state', '')
      date = request.GET.get('date', '')
      time = request.GET.get('time', '')
      seats = request.GET.get('seats', '')

      context['people'] = Person.objects.filter(
            origination_city__icontains=origination_city,
            origination_state__icontains=origination_state,
            destination_city__icontains=destination_city,
            destination_state__icontains=destination_state,
            date__icontains=date,
            time__icontains=time,
            seats_available__icontains=seats
        )
      return render(request, 'search_results.html', context)

  context['form'] = RideForm()
  return render(request, 'index_view.html', context)

def create(request):
  if request.method == "POST":
    new_ride = NewRideForm(request.POST)
    new_ride.save()
  return redirect("/rides")

def create_rides(request):
  context = {}
  context["new_ride_form"] = NewRideForm()
  return render(request, "create_rides.html",context)


def display_rides(request):
  return render(request, "search_results.html")

HandyRides Lab3/rides/templates/create_rides.html
{% extends "index_view.html" %}
{% load static %}

<html>
<head>
    <title>ConnectCarpool</title>
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
    <script src="{% static 'main.js' %}"></script>
</head>
<body>
  {% block content %}
  <div class = 'form-container'>
    <center>
      <h2>Post a Ride</h2>
        <form action="{% url 'rides:create' %}" method="post">
          {% csrf_token %}
          <div>
            <label for="{{ new_ride_form.first_name.id_for_label }}">First name:</label>
            {{ new_ride_form.first_name }}
          </div>
          <div>
            <label for="{{ new_ride_form.last_name.id_for_label }}">Last name:</label>
            {{ new_ride_form.last_name }}
          </div>
          <div>
            <label for="{{ new_ride_form.email.id_for_label }}">Email:</label>
            {{ new_ride_form.email }}
          </div>
          <div>
            <label for="{{ new_ride_form.phone_number.id_for_label }}">Phone Number:</label>
            {{ new_ride_form.phone_number }}
          </div>
          <div>
            <label for="{{ new_ride_form.origination_city.id_for_label }}">Origination City:</label>
            {{ new_ride_form.origination_city }}
          </div>
          <div>
            <label for="{{ new_ride_form.origination_state.id_for_label }}">Origination State:</label>
            {{ new_ride_form.origination_state }}
          </div>
          <div>
            <label for="{{ new_ride_form.destination_city.id_for_label }}">Destination City:</label>
            {{ new_ride_form.destination_city }}
          </div>
          <div>
            <label for="{{ new_ride_form.destination_state.id_for_label }}">Destination State:</label>
            {{ new_ride_form.destination_state }}
          </div>
          <div>
            <label for="{{ new_ride_form.vehicle_type.id_for_label }}">Vehicle Type:</label>
            {{ new_ride_form.vehicle_type }}
          </div>
          <div>
            <label for="{{ new_ride_form.vehicle_model.id_for_label }}">Vehicle Model:</label>
            {{ new_ride_form.vehicle_model }}
          </div>
          <div>
            <label for="{{ new_ride_form.date.id_for_label }}"> Date:</label>
            {{ new_ride_form.date }}
          </div>
          <div>
            <label for="{{ new_ride_form.time.id_for_label }}"> Time:</label>
            {{ new_ride_form.time }}
          </div>
          <div>
            <label for="{{ new_ride_form.taking_passengers.id_for_label }}"> Taking Passengers:</label>
            {{ new_ride_form.taking_passengers }}
          </div>
          <div>
            <label for="{{ new_ride_form.seats_available.id_for_label }}"> Seats Available:</label>
            {{ new_ride_form.seats_available }}
          </div>
          <input type="submit" value="Post Ride">
        </form>
    </center>
    </div>
  {% endblock %}

</body>
</html>

HandyRides Lab3/rides/templates/index_view.html
{% load static %}

<html>
<head>
  <title>ConnectCarpool</title>
  <link rel="stylesheet" href="{% static 'main.css' %}"/>
  <script src="{% static 'main.js' %}"></script>
</head>
<body>
  <nav class="navbar">
    <a href="{% url 'rides:index' %}">Find Ride</a>
    <a href="{% url 'rides:create_rides' %}">Create Ride</a>
  </nav>
  {% block content %}
  <center>
    <h1>ConnectCarpool</h1>
    <img src="{% static 'Hrides_search.jpg' %}" width =450 height =400 alt="TheCarpool.com Company Logo"><br>
    <h2>Search For Ride</h2>
    <div class="main"> 
    </div> 
    <form action="{% url 'rides:index' %}" method="get" onsubmit="return checkForm(this);">
      <div>
        <label for="{{ ride_form.origination_city.id_for_label }}">Origination City:</label>
        {{ form.origination_city }}
      </div>
      <div>
        <label for="{{ ride_form.origination_state.id_for_label }}">Origination State:</label>
        {{ form.origination_state }}
      </div>
      <div>
        <label for="{{ ride_form.destination_city.id_for_label }}">Destination City:</label>
        {{ form.destination_city }}
      </div>
      <div>
        <label for="{{ ride_form.destination_state.id_for_label }}">Destination State:</label>
        {{ form.destination_state }}
      </div>
      <div>
        <label for="{{ ride_form.date.id_for_label }}">Date:</label>
        {{ form.date }}
      </div>
      <div>
        <label for="{{ ride_form.time.id_for_label }}"> Time:</label>
        {{ form.time }}
      </div>
      <div>
        <label for="{{ ride_form.seats.id_for_label }}"> Seats:</label>
        {{ form.seats }}
      </div>            
      <input type="submit" value="Find Ride"> 
    </form>
  </center>
  
  {% endblock %}
</body>
</html>

HandyRides Lab3/rides/templates/search_results.html
{% load static %}

<html>
<head>
  <title>ConnectCarpool</title>
  <link rel="stylesheet" href="{% static 'main.css' %}"/>
  <script src="{% static 'main.js' %}"></script>
</head>
<body>
  <nav class="navbar">
    <a href="{% url 'rides:index' %}">Find Ride</a>
    <a href="{% url 'rides:create_rides' %}">Create Ride</a>
  </nav>
  {% block content %}
  <center>
    <h1>ConnectCarpool</h1>
    <img src="{% static 'Hrides_search.jpg' %}" width =450 height =400 alt="TheCarpool.com Company Logo"><br>
    <div class="main"> 
      <table>
      <thead>
          <tr>
            <th>First Name</th>
            <th>Origination City</th>
            <th>Origination State</th>
            <th>Destination City</th>
            <th>Destination State</th>
            <th>Date</th>
            <th>Time</th>
            <th>Taking Passengers</th>
            <th>Seats Available</th>
          </tr>
        </thead>
          {% for person in people %}
          <tr>
              <td>{{ person.first_name }}</td> 
              <td>{{ person.origination_city}}</td>
              <td>{{ person.origination_state}}</td>
              <td>{{ person.destination_city }}</td> 
              <td>{{ person.destination_state }}</td> 
              <td>{{ person.date }}</td> 
              <td>{{ person.time }}</td> 
              <td>{{ person.taking_passengers }}</td>
              <td>{{ person.seats_available }}</td> 
          </tr>
          {% endfor %} 
      </table>
    </div> 
  </center>
  
  {% endblock %}
</body>
</html>

HandyRides Lab3/templates/base.html
{% load static %}

<html>
<head>
    <script src="{% static 'main.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
    <title>ConnectCarpool</title>
</head>
<body bgcolor="white" text="black">
    <center>
        <h1>ConnectCarpool</h1>
        {% block content %}
        {% endblock %}
    </center>
</body>
</html>

HandyRides Lab3/templates/index.html
<!--copies the base html format and now one can iterate on it-->
{% extends "base.html" %}
{% load static %}

<html>
<head>
    <script src="{% static 'main.js' %}"></script>
</head>
<body bgcolor="white" text="black">
    <center>
        {% block content %}
        <img src="{% static 'pixlr-image-generator-65d41d355b01a801800720ab.png' %}" width =450 height =400 alt="TheCarpool.com Company Logo" class = "homepage-image"><br>
        <h2> Welcome</h2>
        <h2> ConnectCarpool is a company dedicated to helping you find people with enough in common to casually share rides. Whether you are going to a sports event or attending an important business conference, ConnectCarpool helps you find people who are attending the same event and coordinate travel together.</h2>
        <a href="{% url 'rides:index' %}" class="button">Find Your Ride!</a>
        <script>
            // When the window loads, check the cookie
            window.onload = function() {
                checkCookie();
            };
        </script>
        {% endblock %}
    </center>
</body>
</html>